Copiar un array de NumPy
Al ser mutables, para copiar un ndarray lo mejor es usar array1.copy() o nuevamente np.array(array1).

In [1]:
import numpy as np

In [5]:
# Forma incorrecta de copiar un array. Ya que al modificar
# un array se modifica tmb la copia

A1 = np.array([2, 4, 6])
A2 = A1
A1[0] = 8
print(A1)
print(A2)

print("\n\n")
# Forma correcta de copiar un array. Ya que al modificar
# un array no se modificar su copia. 

a1 = np.array([2, 4, 6])
a2 = a1.copy()
a1[0] = 8
print(a1)
print(a2)


[8 4 6]
[8 4 6]



[8 4 6]
[2 4 6]
