Manipulando arrays
Es hora de manipular los arrays. De manera muy parecida a las listas, los ndarrays permiten hacer slicing con la notación [filas, columnas] y sus índices inician en 0.

Se puede hacer slicing con esta notación [2:5, 3:6]. Para seleccionar toda una columna o fila, se usa :. Por ejemplo:

[1, :] ← esto selecciona todas las columnas de la segunda fila.
[:, 2] ← esto selecciona todas las filas de la tercera columna.
Veamos algunos ejemplos con una matriz para que quede más claro.

In [1]:
import numpy as np

In [3]:
matrix_cool = np.arange(9).reshape(3, 3)
print(matrix_cool)
print("\n")
print(matrix_cool[1, 2])
print("\n")
print(matrix_cool[0, :])
print("\n")
print(matrix_cool[:, 1])
print("\n")
print(matrix_cool[:, 1:])
print("\n")
print(matrix_cool[0:2, 0:2])
print("\n")
print(matrix_cool[:, :])


[[0 1 2]
 [3 4 5]
 [6 7 8]]


5


[0 1 2]


[1 4 7]


[[1 2]
 [4 5]
 [7 8]]


[[0 1]
 [3 4]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
