Ahora que ya dominas los conceptos básicos, es hora de ponerlos en acción. Te dejaré una serie de ejercicios, resuélvelos con la ayuda de NumPy y deja tu código con sus resultados en los comentarios.

Para esto te he dejado en el notebook que te compartí al inicio una base de datos de jugadores de beisbol, la cual tiene 2 columnas principales: altura (pulgadas) y peso (libras). No te preocupes, en el notebook ya te las dejé listas como ndarrays con el nombre de height y weight. Esto es lo que tienes que hacer:

Crea un nuevo array en el que transformes las unidades de las alturas a metros (pista: multiplica por 0.0254).
Crea un nuevo array en el que transformes las unidades de los pesos a kilogramos (pista: multiplica por 0.453592).
Ahora vas a crear un nuevo array en el que calcules el IMC (Índice de Masa Corporal) de los jugadores a partir de los 2 vectores que creaste (pista: la fórmula es peso / altura²).
¿Cuál es el máximo IMC? ¿Y el mínimo?
¿Cuál es la media y la mediana del IMC? ¿Los valores son cercanos o hay un sesgo en los datos?
¿Qué hay de la desviación estándar?
¿Cuál es el peso y altura del jugador #734? ¿Es posible unificar los vectores en una matriz para obtener este resultado?
Esto último no lo vimos en el tutorial, así que será un reto para ti. Vas a intentar filtrar los datos para obtener cuántos jugadores tienen un IMC por debajo de 21 (pista: es posible hacerlo en una línea).

In [21]:
import numpy as np
import pandas as pd

In [22]:
# Defino mi dataframe para luego seleccionar mis variables
df = pd.read_csv("./archivos_csv/Baseball_Players.csv")
df

Name Team        Position  Height(inches)  Weight(pounds)  \
0       Adam_Donachie  BAL         Catcher              74             180   
1           Paul_Bako  BAL         Catcher              74             215   
2     Ramon_Hernandez  BAL         Catcher              72             210   
3        Kevin_Millar  BAL   First_Baseman              72             210   
4         Chris_Gomez  BAL   First_Baseman              73             188   
...               ...  ...             ...             ...             ...   
1029    Brad_Thompson  STL  Relief_Pitcher              73             190   
1030    Tyler_Johnson  STL  Relief_Pitcher              74             180   
1031   Chris_Narveson  STL  Relief_Pitcher              75             205   
1032    Randy_Keisler  STL  Relief_Pitcher              75             190   
1033      Josh_Kinney  STL  Relief_Pitcher              73             195   

        Age  
0     22.99  
1     34.69  
2     30.78  
3     35.43  
4     35.71  
...     ...  
1029  25.08  
1030  25.73  
1031  25.19  
1032  31.01  
1033  27.92  

[1034 rows x 6 columns]

In [23]:
altura = df["Height(inches)"].to_numpy(dtype="int64")
peso = df["Weight(pounds)"].to_numpy(dtype="int64")

In [24]:
altura

array([74, 74, 72, ..., 75, 75, 73], dtype=int64)

In [25]:
peso

array([180, 215, 210, ..., 205, 190, 195], dtype=int64)

In [26]:
altura = altura * 0.0254 # Transformo altura de pulgadas a metros
altura

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [27]:
peso = peso * 0.453592 # Transformo peso de libras a kilos
peso

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [28]:
arr_imc = peso / (altura**2)
arr_imc

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

In [29]:
maximo = np.max(arr_imc)
minimo = np.min(arr_imc)

print(maximo) # Máximo de IMC
print(minimo) # Mínimo de IMC

35.26194861031698
19.498447103560874


In [30]:
media = np.mean(arr_imc)
mediana = np.median(arr_imc)

print(media)
print(mediana)


26.098429191546032
26.08790375280194


Los valores son muy cercanos por lo que no hay un sesgo en los datos. 

In [31]:
desviacion_estandar = np.std(arr_imc)

print(desviacion_estandar)

2.3036717894936576


    Cuál es el peso y altura del jugador #734? ¿Es posible unificar los vectores en una matriz para obtener este resultado?
    Esto último no lo vimos en el tutorial, así que será un reto para ti. Vas a intentar filtrar los datos para obtener cuántos jugadores tienen un IMC por debajo de 21 (pista: es posible hacerlo en una línea).

In [32]:
peso734 = peso[733]
peso734

86.18248

In [33]:
altura734 = altura[733]
altura734

1.8034

In [34]:
matriz_peso_altura = np.array([peso , altura]) # Uso el array con corchetes dentro del mismo y las listas que quiero integrar separadas por comas para hacer
# una matriz única con pesos y alturas.  
print(matriz_peso_altura)

[[81.64656 97.52228 95.25432 ... 92.98636 86.18248 88.45044]
 [ 1.8796   1.8796   1.8288  ...  1.905    1.905    1.8542 ]]


In [35]:
print(np.shape(matriz_peso_altura)) # Me indica las dimensiones de mi matriz. Primero las filas y luego las columnas
print(matriz_peso_altura[0: ,733:734]) 


(2, 1034)
[[86.18248]
 [ 1.8034 ]]


In [36]:
arr_imc_21 = [values for values in arr_imc if values < 21] # Resolví el desafio usando list comprehensions
print(arr_imc_21)

[20.542556790007662, 20.542556790007662, 20.69282047151352, 20.69282047151352, 20.343431890567484, 20.343431890567484, 20.69282047151352, 20.158834718074228, 19.498447103560874, 20.69282047151352, 20.92052190452328]


In [37]:
print(arr_imc[arr_imc<21])
print(arr_imc[arr_imc<21].shape) # El shape se puede usar como metodo tambien luego de un arreglo para saber su largo.

[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]
(11,)
