Retos:
Crea un tensor 3D a partir de listas.
Crea un array con 100 valores entre 6 y 9.
Haz que el anterior array ahora tenga todos sus valores iguales a pi.
Crea un array 1D de 10000 números aleatorios.

In [1]:
import numpy as np
import matplotlib.pyplot as plt 

In [23]:
my_list = [1,2,3,4,5,6,7,8,9,10]
my_list2 = [11,12,13,14,15,16,17,18,19,20]
my_list3 = [21,22,23,24,25,26,27,28,29,30]
my_super_list =[[my_list],[my_list2],[my_list3]]

In [25]:
tensor3d = np.array(my_super_list + my_super_list)
tensor3d

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]])

In [34]:
vector = np.linspace(6,9,100)
vector

array([6.        , 6.03030303, 6.06060606, 6.09090909, 6.12121212,
       6.15151515, 6.18181818, 6.21212121, 6.24242424, 6.27272727,
       6.3030303 , 6.33333333, 6.36363636, 6.39393939, 6.42424242,
       6.45454545, 6.48484848, 6.51515152, 6.54545455, 6.57575758,
       6.60606061, 6.63636364, 6.66666667, 6.6969697 , 6.72727273,
       6.75757576, 6.78787879, 6.81818182, 6.84848485, 6.87878788,
       6.90909091, 6.93939394, 6.96969697, 7.        , 7.03030303,
       7.06060606, 7.09090909, 7.12121212, 7.15151515, 7.18181818,
       7.21212121, 7.24242424, 7.27272727, 7.3030303 , 7.33333333,
       7.36363636, 7.39393939, 7.42424242, 7.45454545, 7.48484848,
       7.51515152, 7.54545455, 7.57575758, 7.60606061, 7.63636364,
       7.66666667, 7.6969697 , 7.72727273, 7.75757576, 7.78787879,
       7.81818182, 7.84848485, 7.87878788, 7.90909091, 7.93939394,
       7.96969697, 8.        , 8.03030303, 8.06060606, 8.09090909,
       8.12121212, 8.15151515, 8.18181818, 8.21212121, 8.24242

In [36]:
vector = np.full_like(vector, np.pi)
vector

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159

In [39]:
vector2 = np.random.randint(0,100,100) # Hago 100 porque 10000 no los muestra por pantalla
vector2

array([62, 40, 82, 10, 35, 10, 17, 95, 75, 14, 63, 10, 10, 26, 57, 10, 58,
       92, 20, 48, 12, 98,  5, 11,  9, 56,  3, 35, 76, 20, 78, 14,  0,  0,
       47, 46, 93,  9, 15,  8, 51, 36, 56, 24,  5, 24, 28, 73, 95, 13, 13,
       85, 26, 40, 42, 72, 38, 19, 78, 70, 30, 23, 68, 76, 16, 98, 71, 84,
       24, 51,  8, 56, 44, 69, 75, 13, 27,  1, 59, 65, 78, 66, 12, 84, 12,
       90, 89, 94, 89, 24, 45, 19, 79, 31, 40, 66, 83, 11, 28, 30])