Reto:
Intenta crear un array con diferentes tipos de datos (por ejemplo, enteros y flotantes). ¿Si usas .dtype(), qué tipo de dato es?
Crea una matriz de 10 × 10 a partir de un vector secuencial (analiza cuál es la mejor solución, usar np.arange o np.linspace).

In [1]:
import numpy as np

In [3]:
vector = np.array([1,1.5,2,2.5,3,3.1417,3.5,4,4.67,5])
vector

array([1.    , 1.5   , 2.    , 2.5   , 3.    , 3.1417, 3.5   , 4.    ,
       4.67  , 5.    ])

In [5]:
vector.dtype # Al pasarle a un arreglo enteros y flotantes, el arreglo unifica todo en un solo tipo de dato, en este caso flotante.

dtype('float64')

In [16]:
vector2 = np.arange(1,101,1)
print(vector2)
vector3 = vector2.reshape(10,10)
print(vector3)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
