Tamaño de los arrays
Hay un par de funciones y métodos que te ayudarán a saber las dimensiones que un array y su tipo de datos:

.shape: devuelve las dimensiones del array. Para una matriz el primer valor son las filas y el segundo las columnas. Para un tensor el primer valor es la “profundidad”, el segundo las filas y el tercero las columnas.
.reshape(): redimensiona un array, es decir, te permite crear matrices o tensores a partir de vectores y viceversa. También funciona como método.
.dtype: devuelve el tipo de dato de un array.

In [1]:
import numpy as np

In [2]:
C = np.arange(1, 9).reshape(2, 2, 2)
print(C)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
a = np.arange(1,10)
B = np.reshape(a, [3,3])
print(a)
print(B)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.shape(a))
print(np.shape(B))
print(a.dtype) # dtype se usa como metodo de una variable tipo arreglo

(9,)
(3, 3)
int32
